### ISSUE TITLE
`getproperty` for `UmfpackLU` always extracts all fields

### ISSUE THREAD

**Issue by ElOceanografo** [JuliaLinearAlgebra/SuiteSparse.jl#9]
The `getproperty` [method](https://github.com/JuliaLinearAlgebra/SuiteSparse.jl/blob/4c3efa357aed9c4da8c7465bce69acf35986435f/src/umfpack.jl#L469) for `UmfpackLU` extracts all fields for the object, then discards the ones that weren't requested.  This is clearly suboptimal for performance, an issue which I've run into [here](https://github.com/JuliaLang/julia/pull/38476).

Umfpack should allow extracting just one of the fields of the `UmfpackLU` structure by passing in null values for the unwanted arguments--see top of page 94 in the Umfpack docs ([PDF](https://fossies.org/linux/SuiteSparse/UMFPACK/Doc/UMFPACK_UserGuide.pdf)).  It would be great to modify the `getproperty` and/or `extract_umf` methods to allow extracting just one field at a time to avoid unnecessary allocations.

**Comment by andreasnoack** [comment]
Please notice that SuiteSparse still resides in the main Julia repo, so this issue actually belongs there. It would also be great if you could prepare a PR with the suggested change. If you do that, feel free to ping me and I'll review it.

**Comment by ElOceanografo** [comment]
Ok, I'll close this one and open an issue in the main repo.  I already took a stab at a new `getproperty` method, but was getting unknown error codes from Umfpack that I haven't figured out yet.  I'll ping you if I make enough progress for a PR.
